name: "Cloudflare Dynamic DNS"
description: "Update dynamic DNS record hosted with Cloudflare"
version: 1.0.0
slug: "cloudflare_ddns"
init: false
arch:
    - aarch64
    - amd64
    - armhf
    - armv7
    - i386
options:
    domains:
        - null
    token: null
    zone_id: null
    update_interval: 300
schema:
    domains: []
    token: str
    zone_id: str
    update_interval: int
