name: "Cloudflare Dynamic DNS"
description: "Update dynamic DNS record hosted with Cloudflare"
version: "1.0.0"
slug: "cloudflare_ddns"
arch:
    - aarch64
    - amd64
    - armhf
    - armv7
    - i386

