name: "Cloudflare Dynamic DNS"
description: "Update dynamic DNS record hosted with Cloudflare"
version: 1.0.1
slug: "cloudflare_ddns"
init: false
arch:
    - aarch64
    - amd64
    - armhf
    - armv7
    - i386
schema:
    domains:
      - str
    token: str
    zone_id: str
    update_interval: int
