name: "Cloudflare Dynamic DNS"
description: "Update dynamic DNS record hosted with Cloudflare"
url: "https://github.com/theasianpianist/home-assistant/tree/main/cloudflare_ddns"
version: 1.2.1
image: "theasianpianist/cloudflare_ddns"
slug: "cloudflare_ddns"
init: false
arch:
    - aarch64
    - amd64
    - armhf
    - armv7
    - i386
schema:
    domains:
      - "str?"
    proxy_domains:
      - "str?"
    token: str
    zone_id: str
    update_interval: int
